export const dataPlayers = [
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 4,
    kills: 8,
    defeat: 2,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-ambessa.png`,
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
  {
    id: 'WildDev#WDEV',
    name: 'WildDev',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: '',
  },
]