export const dataPlayers = [
  {
    id: 'Blade#2656',
    name: 'Blade',
    elo: 'Maestro',
    puntos: 1,
    kills: 1,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-yone.webp`,
    wo: 0,
  },
  {
    id: 'AS Khyone nevah#Lux',
    name: 'AS Khyone nevah',
    elo: 'Maestro',
    puntos: 1,
    kills: 1,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-lux.webp`,
    wo: 0,
  },

  {
    id: 'LF CHIMUELO #famk',
    name: 'LF CHIMUELO',
    elo: 'Maestro',
    puntos: 1,
    kills: 1,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-mundo.webp`,
    wo: 0,
  },

  {
    id: 'LFN LARRYCALECHE#AÑA',
    name: 'LFN LARRYCALECHE',
    elo: 'Diamante',
    puntos: 1,
    kills: 1,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-ekko.webp`,
    wo: 0,
  },

  {
    id: 'Oris 先輩#PRO',
    name: 'Oris 先輩',
    elo: 'Retador',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-ahri.webp`,
    wo: 1,
  },

  {
    id: 'AS Kytzon#Kayn',
    name: 'AS Kytzon',
    elo: 'Retador',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-kayn.webp`,
    wo: 1,
  },
  
  {
    id: 'AngHell#616',
    name: 'AngHell',
    elo: 'Maestro',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-akali.webp`,
    wo: 1,
  },

  {
    id: 'Darck#GV7',
    name: 'Darck',
    elo: 'Maestro',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-ahri.webp`,
    wo: 1,
  },

  {
    id: 'redencionArc#0101',
    name: 'redencionArc',
    elo: 'Diamante',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-sett.webp`,
    wo: 1,
  },

  {
    id: 'hacali#CALCO',
    name: 'hacali',
    elo: 'Diamante',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-akali.webp`,
    wo: 1,
  },
  
  {
    id: 'JHORMAR OTP#GWEN',
    name: 'JHORMAR OTP',
    elo: 'Diamante',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-darius.webp`,
    wo: 1,
  },
  
  {
    id: 'Venta de kamas#Tuki',
    name: 'Venta de kamas',
    elo: 'Diamante',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-akali.webp`,
    wo: 1,
  },
  {
    id: 'SDKTLACAELELSDK#LAN',
    name: 'SDKTLACAELELSDK',
    elo: 'Diamante',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-twitch.webp`,
    wo: 1,
  },

  {
    id: 'NovemberAjax#SUPP',
    name: 'NovemberAjax',
    elo: 'Diamante',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-nami.webp`,
    wo: 1,
  },

  {
    id: 'GIR4LDO 冠#000',
    name: 'GIR4LDO 冠',
    elo: 'Esmeralda',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-kaisa.webp`,
    wo: 1,
  },

  {
    id: 'Nia#1528',
    name: 'Nia',
    elo: 'Platino',
    puntos: 0,
    kills: 0,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-vex.webp`,
    wo: 1,
  },
]