export const dataPlayers = [
  {
    id: 'Blade#2656',
    name: 'Blade',
    elo: 'Maestro',
    puntos: 3,
    kills: 4,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-yone.webp`,
    wo: 0,
  },

  {
    id: 'LF CHIMUELO #famk',
    name: 'LF CHIMUELO',
    elo: 'Maestro',
    puntos: 2,
    kills: 3,
    defeat: 0,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-mundo.webp`,
    wo: 1,
  },
  {
    id: 'LFN LARRYCALECHE#AÑA',
    name: 'LFN LARRYCALECHE',
    elo: 'Diamante',
    puntos: 2,
    kills: 3,
    defeat: 1,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-ekko.webp`,
    wo: 0,
  },
  {
    id: 'Venta de kamas#Tuki',
    name: 'Venta de kamas',
    elo: 'Diamante',
    puntos: 2,
    kills: 2,
    defeat: 1,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-akali.webp`,
    wo: 1,
  },

  {
    id: 'GIR4LDO 冠#000',
    name: 'GIR4LDO 冠',
    elo: 'Esmeralda',
    puntos: 2,
    kills: 2,
    defeat: 1,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-kaisa.webp`,
    wo: 1,
  },
  {
    id: 'AS Khyone nevah#Lux',
    name: 'AS Khyone nevah',
    elo: 'Maestro',
    puntos: 1,
    kills: 2,
    defeat: 2,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-lux.webp`,
    wo: 0,
  },

  {
    id: 'Darck#GV7',
    name: 'Darck',
    elo: 'Maestro',
    puntos: 1,
    kills: 1,
    defeat: 2,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-ahri.webp`,
    wo: 2,
  },

  {
    id: 'redencionArc#0101',
    name: 'redencionArc',
    elo: 'Diamante',
    puntos: 0,
    kills: 0,
    defeat: 3,
    catImg: `${import.meta.env.BASE_URL}cat-players/cat-sett.webp`,
    wo: 3,
  },
]